In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/data/Advertising.csv')

In [4]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [6]:
df.corr()

TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [7]:
X = df.drop('sales',axis=1)

In [8]:
y = df['sales']

In [9]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(degree =3,include_bias = False)

In [10]:
poly_features = polynomial_converter.fit_transform(X)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(poly_features,y,test_size = 0.33,random_state = 101)

In [12]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# we pewrform ridege,lasso and elastic net  regression 

In [13]:
from sklearn.linear_model import Ridge
ridge_model = Ridge(alpha = 10)


In [14]:
ridge_model.fit(X_train,y_train)
y_pred = ridge_model.predict(X_test)

In [17]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

In [18]:
mae,mse,rmse

(0.5541835900915879, 0.741204249294152, 0.8609321978496053)

In [19]:
#now we perform ridege regression with different values of alpha

In [20]:
from sklearn.linear_model import RidgeCV
ridge_cv_model = RidgeCV(alphas = [0.1,1,10,20],scoring = 'neg_mean_absolute_error')

In [21]:
ridge_cv_model.fit(X_train,y_train)
y_pred1 =ridge_cv_model.predict(X_test)

In [22]:
mae1 = mean_absolute_error(y_test,y_pred1)
mse1 = mean_squared_error(y_test,y_pred1)
rmse1 = np.sqrt(mse1)

In [23]:
mae1,mse1,rmse1

(0.41901199532667244, 0.3608048125243656, 0.6006703026822331)

In [25]:
ridge_cv_model.coef_

array([ 5.32298502,  0.6340435 ,  0.45082   , -6.01678743,  4.5650384 ,
       -1.05529106, -1.25112885,  0.47865005, -0.21808315,  2.49274371,
       -1.43382273,  0.77165384,  0.70388686, -0.28850266,  0.18532879,
        0.48908704, -0.1470775 , -0.01268636, -0.03643881])

In [26]:
# Lasso regression

In [28]:
from sklearn.linear_model import LassoCV
lasso_cv_model = LassoCV(eps=0.1,n_alphas= 100,cv=5)
lasso_cv_model.fit(X_train,y_train)
y_pred2=lasso_cv_model.predict(X_test)

In [29]:
mae2 = mean_absolute_error(y_test,y_pred2)
mse2 = mean_absolute_error(y_test,y_pred2)
rmse2 = np.sqrt(mse2)

In [30]:
mae2,mse2,rmse2

(0.6302901710051617, 0.6302901710051617, 0.7939081628281458)

In [31]:
lasso_cv_model.coef_

array([1.01555096, 0.        , 0.        , 0.        , 3.69769186,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [36]:
from sklearn.linear_model import ElasticNetCV
elsticnetcv_model = ElasticNetCV(l1_ratio = [0.1,0.5,0.9,0.95,0.99,1],tol = 0.1)


In [37]:
elsticnetcv_model.fit(X_train,y_train)
y_pred3 = elsticnetcv_model.predict(X_test)

In [38]:
mae3 = mean_absolute_error(y_test,y_pred3)
mse3 = mean_squared_error(y_test,y_pred3)
rmse3 = np.sqrt(mse3)

In [39]:
mae3,mse3,rmse3

(0.6871615231090895, 0.8358379196047547, 0.9142417183681538)

In [40]:
elsticnetcv_model.coef_

array([ 3.50291741,  2.41774784,  0.23606964, -0.53558854,  1.39217874,
       -0.19061631, -0.72460372, -0.02348321, -0.02642768, -0.83253312,
        0.95186131, -0.10634132,  0.43375609, -0.        ,  0.00998688,
       -0.58685471, -0.02421073, -0.04376887, -0.        ])